# Generated by Django 5.2.9 on 2025-12-30 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_property_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='agents', to='core.property'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For sale'), ('for_lease', 'For Lease'), ('for_rent', 'For rent'), ('sold', 'Sold')], default='for_sale', max_length=20),
        ),
    ]
