# Generated by Django 5.2.9 on 2025-12-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_municipality_property_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
