# Generated by Django 5.2.9 on 2026-01-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_property_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
