# Generated by GitHub Copilot on 2026-01-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_service_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.URLField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
